### ISSUE TITLE
installing auto update other libraries

### ISSUE THREAD

**Issue by DeoLeung** [codejamninja/sphinx-markdown-builder#1]
when pip install this library, it auto update my other libraries, that may not be good

**Comment by clayrisser** [comment]
I suggest using a virtual environment.

```sh
sudo pip3 install virtualenv
cd <PROJECT_DIR>
virtualenv env && source ./env/bin/activate
pip3 install -r requirements.txt
pip3 install sphinx-markdown-builder
```

**Comment by clayrisser** [comment]
I directly embedded `doctree2md`. This may help with the install. At any rate, it cuts back on a lot of unused required dependencies. Update to version `0.1.0`.

**Comment by mateusccoelho** [comment]
Hi, in a very limited environment (my case) I can't use virtual environments, so I had troubles installing the package due to dependencies versions. I had to manually change each entry in requirements.txt to the versions I already had installed so that neither dependencies would be installed not pip tried to auto update them. It turns out that it worked.

So, I suggest you to figure out what are the lowest versions of your dependencies that works.

**Comment by clayrisser** [comment]
Ok, thanks for letting me know about this. I don't know when I will get around to this. Would you mind letting me know the versions you are using, to help jumpstart the process?

Better yet, you could go through and test the lowest versions yourself and then do a pull request.

**Comment by eode** [comment]
This also pins Sphinx at 1.8.1 (1.8.2 is out -- perhaps `Sphinx>=1.8` or similar might be good)

**Comment by clayrisser** [comment]
Thanks, @eode, I'll take a look when I get around to it. Feel free to submit a pull request.

**Comment by eode** [comment]
PR #6 permits libraries to be upgraded.  This does not fix the issue that @DeoLeung created, but it fixes my related issue.

To fix the original issue, the following would be needed:
* test coverage for expected feature functionality
* discovering which lower versions of selected libraries work
  * This probably requires bumping versions down, testing, bumping down, testing [...], but could be
    done more quickly by someone familiar with all of the APIs and projects used.

**Comment by clayrisser** [comment]
Ok cool, thanks for the pr
