### ISSUE TITLE
Preserve language domain when converting language blocks

### ISSUE THREAD

**Issue by Liam-Deacon** [codejamninja/sphinx-markdown-builder#13]
Markdown conversion does not preserve restructuredtext code blocks such as:

```restructuredtext

.. code-block:: python
    import math

.. literalinclude:: test.py
    :language: python

.. highlight:: bash

::
    cat *.rst

```

And render it in markdown as (without the spaces I've used as escape characters for the backticks):

```

`` `python
import math
` ``

...

`` `bash
cat *.rst
` ``

```

**Comment by clayrisser** [comment]
Can you create an example repo and send it to me to test?

**Comment by Liam-Deacon** [comment]
Hi @codejamninja - I've setup an example within https://github.com/Lightslayer/sphinx-automodule-example under `docs/source/codeblocks.rst`

For reference this is what I get as markdown output (note I've manually delimited the backticks with spaces here so that it would render better inside this comment's markdown block):

```markdown
# example code block

First code block below is in python syntax, showing line numbering and emphasizing line 2:

`` `
import math
print(math.sqrt(9))
` ``

Second is in bash:

`` `
echo "some stuff" 1>&2
ls /etc/
`` `

(and using highlight directive):

`` `
echo "some stuff" 1>&2
ls /etc/
`` `

Finally a literal include:

`` `
"""A very dumb example"""
import numpy as np
import pandas as pd

print("{mod}".format(mod=np))
`` `

```

**Comment by duffau** [comment]
I have encountered the same issue when setting the language in literal blocks.

In `doctree2md.py` about line 492 in the `visit_literal_block` method i can see a check for 
an attribute called 'force_highlighting':

```python
    def visit_literal_block(self, node):
        self._escape_text = False
        code_type = node['classes'][1] if 'code' in node['classes'] else ''
        if node.get('force_highlighting', False) and 'language' in node:
            code_type = node['language']
        self.add('```' + code_type + '\n')
```

In my understanding the from the  [sphinx code-block directive docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block) the option is called "force".  The "force_highlighting" option doesn't exist and raises a warning.

Wen inspecting the `node` i see a 'force' attribute. 

So I suggest to change the check from,
```python
node.get('force_highlighting', False)
```   
to
```python
node.get('force', False)
```

Should I make a PR with this change?

```
python 3.6.9
sphinx == 2.4.4
sphinx-markdown-builder==0.5.4
```

**Comment by clayrisser** [comment]
Thanks @duffau
