### ISSUE TITLE
Feature Request: Add option to preserve TOC tree order

### ISSUE THREAD

**Issue by Liam-Deacon** [codejamninja/sphinx-markdown-builder#14]
It would be great if there was an option to allow the generated markdown files to be prefixed with their TOC numbering (which would work on most sites)

**Comment by Liam-Deacon** [comment]
Please note I've setup an example within https://github.com/Lightslayer/sphinx-automodule-example with multiple restructured text files referenced in index.rst

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
