### ISSUE TITLE
Feature Request: Add support for plot directive

### ISSUE THREAD

**Issue by Liam-Deacon** [codejamninja/sphinx-markdown-builder#15]
Another great feature would be to allow use of the [matplotlib plot directive](https://matplotlib.org/devel/plot_directive.html), for example:

```restructuredtext

.. plot::

    import matplotlib.plot as plt 
    plt.plot([0,1], [2, -2])
   
```

**Comment by Liam-Deacon** [comment]
Please note I've setup an example within https://github.com/Lightslayer/sphinx-automodule-example under `docs/source/plot.rst`

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
