### ISSUE TITLE
Feature Request: Add support for graphviz directive

### ISSUE THREAD

**Issue by Liam-Deacon** [codejamninja/sphinx-markdown-builder#16]
Another great feature would be inclusion of graphs given by the [graphviz directive](https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html) for example:

```restructuredtext
.. graphviz:: 
    digraph foo { "bar" -> "baz"; }
```

**Comment by Liam-Deacon** [comment]
Please note I've setup an example within https://github.com/Lightslayer/sphinx-automodule-example under `docs/source/graphviz.rst`

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
