### ISSUE TITLE
Feature Request: Add support for todo directive

### ISSUE THREAD

**Issue by Liam-Deacon** [codejamninja/sphinx-markdown-builder#17]
Another great feature would be inclusion of graphs given by the [todo directive](http://www.sphinx-doc.org/en/master/usage/extensions/todo.html) for example:

```restructuretext

.. todo:: 
    Add todo support ;-)

.. todolist::

```

Please note I've setup an example within https://github.com/Lightslayer/sphinx-automodule-example under `docs/source/todo.rst`

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
