### ISSUE TITLE
Incorrect output when image directive has :target: set

### ISSUE THREAD

**Issue by Liam-Deacon** [codejamninja/sphinx-markdown-builder#18]
Images with targets (hyperlinks) are incorrectly converted as hyperlinks and loose the image, e.g.

```restructuredtext

An image should be included below (without hyperlink):

.. image:: Git-Icon-Black.png

The same image should be included below 
(this time with hyperlink):

.. image:: Git-Icon-Black.png
   :target: https://github.com/codejamninja/sphinx-markdown-builder

example ReST Table
----------------------
...

```

Becomes the following in the markdown output:

```markdown
![image](Git-Icon-Black.png)

The same image should be included below
(this time with hyperlink):

[](https://github.com/codejamninja/sphinx-markdown-builder)## example ReST table

...
```

I've setup an example within https://github.com/Lightslayer/sphinx-automodule-example under the latest `docs/source/other.rst`.

**Comment by clayrisser** [comment]
@Lightslayer, thanks for all the bug reports you filed. This will be extremely helpful to me. It might be a few weeks before I get them knocked out.

**Comment by liran-funaro** [comment]
@Liam-Deacon I created a new plugin that addresses most issues with this implementation.
It also addresses this issue.

You can try it: https://github.com/liran-funaro/sphinx-markdown-builder
I haven't released an official version yet, so you'll have to install it manually: 
```shell
pip3 uninstall sphinx-markdown-builder
pip3 install git+https://github.com/liran-funaro/sphinx-markdown-builder@main
```

**Comment by clayrisser** [comment]
@liran-funaro I am happy to forward people to your fork if you don't mind giving me some credit in your README.md and making a pull request in my README.md file. I no longer use this project, so I lack the motivation to properly maintain it.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
