### ISSUE TITLE
master file ..\docs\contents.rst not found

### ISSUE THREAD

**Issue by ahalota** [codejamninja/sphinx-markdown-builder#19]
I have sphinx-build 1.8.3.

From what I've been following, I only need an index.rst file initially. When I try to run make markdown, it's looking for a file .\docs\contents.rst , which by default I don't have.

I assume this might be configured to work with an older version of sphinx that included a contents.rst by default? 

I created a contents.rst file and put some dummy content in, and then it ran just fine.

**Comment by clayrisser** [comment]
Could you send me an example?

**Comment by Peilonrayz** [comment]
I ran into this the first time I followed the [Sphinx getting started tutorial](http://www.sphinx-doc.org/en/stable/usage/quickstart.html). I noticed that `sphinx-quickstart` made a `index.rst` but in the `conf.py` it had `master_doc = 'contents'`.

Renaming either fixed this for me.

**Comment by clayrisser** [comment]
That doesn't seem like an issue coming from this plugin.

**Comment by Peilonrayz** [comment]
Yeah, for me it wasn't a problem with this plugin. However IDK if it's the same problem for ahalota.
