### ISSUE TITLE
failed on sphinx 1.5.1

### ISSUE THREAD

**Issue by DeoLeung** [codejamninja/sphinx-markdown-builder#2]
better to support some older versions, on `1.5.1` it fails with
```bash
sphinx-build -b markdown doc/ doc/_build/ -E
Running Sphinx v1.5.1
/xxx/.virtualenvs/log/lib/python3.6/site-packages/matplotlib/font_manager.py:232: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '

Extension error:
Could not import extension sphinx_markdown_builder (exception: cannot import name '__')
```

**Comment by clayrisser** [comment]
Are you using python3 and installing with pip3?

**Comment by clayrisser** [comment]
I directly embedded `doctree2md`. This will definitely fix this issue because now the `matplotlib` won't even be installed. At any rate, it cuts back on a lot of unused required dependencies. Update to version `0.1.0`.

**Comment by DeoLeung** [comment]
yes I was using python3

**Comment by codejamninja** [comment]
Can you try again with the newest version?

**Comment by clayrisser** [comment]
Can you try again with the newest version of sphinx-markdown-builder?
