### ISSUE TITLE
toctree is not preserved with links

### ISSUE THREAD

**Issue by ahalota** [codejamninja/sphinx-markdown-builder#20]
toctree outputs a list, but to stay in the same style as html build it should really include links to the appropriate md file.

**Comment by clayrisser** [comment]
Could you setup an example and put a link to it here with some minimal instructions on how to test it?

**Comment by FabianNiehaus** [comment]
I have created an MWE to reproduce this: https://github.com/FabianNiehaus/sphinx-markdown-builder-toctree-test

**Comment by pmatulis** [comment]
I observed this today. When will this change be available?

**Comment by clayrisser** [comment]
I’ll roll a new release tomorrow.

**Comment by kingspp** [comment]
@clayrisser Any updates on this issue? No use in hosting the documentation on git due to missing links.

**Comment by bomany** [comment]
@clayrisser No updates on this yet?

**Comment by clayrisser** [comment]
I just released version `0.5.5`

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
