### ISSUE TITLE
Use version ranges instead of pinning exact versions

### ISSUE THREAD

**Issue by software-opal** [codejamninja/sphinx-markdown-builder#22]
I'm trying to use your library on Python 3 and with Sphinx 2.0.1, and I have noticed that your package pins every package it depends on, this makes it very difficult to use new Sphinx versions.

**Comment by pauleikis** [comment]
Same issue, cannot use library because it's requirements are too strict

**Comment by clayrisser** [comment]
I am sorry about that. I built the `requirements.txt` file by running `pip3 freeze > requirements.txt`.

@software-opal would you be interested in removing the packages it does not depend on and submitting it as a pull request?

**Comment by clayrisser** [comment]
This should be fixed with version `0.5.0`.
