### ISSUE TITLE
Add option to change markdown delimiters.

### ISSUE THREAD

**Issue by Peilonrayz** [codejamninja/sphinx-markdown-builder#27]
Whilst it's common for `math` to use the `$` delimiter, on Code Review it is specified by `\$`.

Can the ability to change the delimiters be made available in `conf.py`?

This would require changing [doctree2md.py#L484](https://github.com/codejamninja/sphinx-markdown-builder/blob/6359cee6c21b9585cef429f668fa64d70e8e3c28/sphinx_markdown_builder/doctree2md.py#L484), but I don't know how to get data from `conf.py`.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
