### ISSUE TITLE
Desc element not yet supported in Markdown.

### ISSUE THREAD

**Issue by mateusccoelho** [codejamninja/sphinx-markdown-builder#3]
I tried to generate docs using this package but it showed 3 warnings: 'The desc element not yet supported in Markdown'. Three files should present a lot of docs but only has titles.

**Comment by clayrisser** [comment]
Could you document which markdown features aren't working? I'm using Matthew Brett's [doctree2md](https://github.com/matthew-brett/nb2plots/blob/master/nb2plots/doctree2md.py) to actually do the conversion.

His markdown writer is a great start, but certainly not complete. I have patched some of his incorrect and incomplete transpiler visitors in the [markdown_writer.py](https://github.com/codejamninja/sphinx-markdown-builder/blob/master/sphinx_markdown_builder/markdown_writer.py) file.

I certainly want to make it eventually fully support all markdown features, however, I have not thoroughly tested which features it supports and does not support.

I have created an issue at the link below to document missing markdown features. Please list any missing features there, and then star the ones that are most important to you to help me prioritize which ones to tackle first.

https://github.com/codejamninja/sphinx-markdown-builder/issues/4
