### ISSUE TITLE
custom node support

### ISSUE THREAD

**Issue by jonathan-taylor** [codejamninja/sphinx-markdown-builder#30]

**Comment by jonathan-taylor** [comment]
Using the markdown builder it seems that translation handlers for new nodes is not working quite correctly. I have a minimal example in which the latex and HTML builders find the correct visit_* and depart_* calls but markdown does not resulting in a call to "unknown_visit".

**Comment by clayrisser** [comment]
Can you send me the example?

**Comment by jonathan-taylor** [comment]
Sure, here's the example and the built code I get for latex,html,markdown.

[build.tar.gz](https://github.com/codejamninja/sphinx-markdown-builder/files/3388447/build.tar.gz)
[minimal_sphinx.tar.gz](https://github.com/codejamninja/sphinx-markdown-builder/files/3388446/minimal_sphinx.tar.gz)

Using this commit:

commit 28187519a81ae9d902dc3d1e4f62083d18d60b25 
Author: Jam Risser <jam@codejam.ninja>
Date:   Fri Jun 28 06:36:14 2019 +0000

    Updated changelog

**Comment by jonathan-taylor** [comment]
One small change to myrole.py to try to set translaters using `add_node` with a markdown keyword.

Using verbose option with sphinx-build you can see that sphinx tries to add the translation handlers for all builders, they just don't seem to be set correctly for the markdown builder, i.e. "unknown_visit" is called on the Translator.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
