### ISSUE TITLE
Documetation outdated

### ISSUE THREAD

**Issue by bennymeg** [codejamninja/sphinx-markdown-builder#32]
Is it possible that the documentation needed to be updated? i.e:
`from sphinx_markdown_builder.markdown_builder import MarkdownBuilder`

`def setup(app):`
`app.add_source_suffix('.md', 'markdown')`
`app.add_source_parser(MarkdownBuilder)`

Also, the python support badge doesn't match the setup file classifiers.

**Comment by clayrisser** [comment]
Thanks for the feedback

**Comment by clayrisser** [comment]
Docs are updated
