### ISSUE TITLE
update requirements file

### ISSUE THREAD

**Issue by bennymeg** [codejamninja/sphinx-markdown-builder#33]
Is it possible to remove the strict version matching for the required packages in favor of the _greater then equals_ sign (`>=`) ?

The package fails on newer versions of _sphinx_ (i.e. 2.2.0) which also installs newer version of _docutils_ (0.15.x).

**Comment by clayrisser** [comment]
Sure thing. I'll get around to it as soon as I can. If you want, you can create a pull request and I will merge it in.

**Comment by clayrisser** [comment]
This should be fixed now
