### ISSUE TITLE
Missing Markdown Features

### ISSUE THREAD

**Issue by clayrisser** [codejamninja/sphinx-markdown-builder#4]
I'm using Matthew Brett's [doctree2md](https://github.com/matthew-brett/nb2plots/blob/master/nb2plots/doctree2md.py) to actually do the conversion.

His markdown writer is a great start, but certainly not complete.

In this issue, please list any markdown features that are broken, missing, or incomplete.

If the community would star the features they most want, that will help me prioritize which ones to tackle first.

**Comment by utf** [comment]
Thanks for developing this, I've been looking for a project like this for a long time.

The markdown features that I would be most interest in are, "topic",  "option_list", "raw" and "desc".

**Comment by clayrisser** [comment]
I just added support for markdown tables created from https://pypi.org/project/sphinx-markdown-tables

**Comment by clayrisser** [comment]
I just added support for inline html

**Comment by Liam-Deacon** [comment]
I've got warnings over the following elements not being supported yet in markdown (almost certainly related to #5 with napoleon): "classifier", "seealso", "citation", "autosummary_toc", as well as "caption".

**Comment by clayrisser** [comment]
Thanks @Lightslayer, I'll try and look into this sometime this week.

**Comment by danielloader** [comment]
Hey, great tool, started using it recently.

My suggestion would be:  WARNING: The [autosummary_toc](http://code.nabla.net/doc/sphinx/api/sphinx/ext/autosummary/sphinx.ext.autosummary.autosummary_toc.html) element not yet supported in Markdown.

Example output:
![image](https://user-images.githubusercontent.com/933423/82425730-d8147e80-9a7e-11ea-89bc-4aa05d9ccf34.png)

Compared to the RTD rendering in html:
![image](https://user-images.githubusercontent.com/933423/82425850-042fff80-9a7f-11ea-9ca9-93491420821e.png)

**Comment by clayrisser** [comment]
@danielloader thanks for this information. Also contributions are most welcome.

**Comment by pmatulis** [comment]
Support is missing for referencing a document with these elements:

```
:doc:`label <some_page>`
```

```
:ref:`label <some_page>`
```

**Comment by clayrisser** [comment]
@pmatulis thanks for documenting this. I do not have time to add support for that at this moment, but a pull request is welcome.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
