### ISSUE TITLE
Directive 'figure' is not supported

### ISSUE THREAD

**Issue by Tilix4** [codejamninja/sphinx-markdown-builder#47]
As a figure works as an image, could it be possible to support the `.. figure::` directive?

**Comment by clayrisser** [comment]
Could you put some links here explaining the figure directive. I'm not very familiar with it and I think the example would be helpful for this thread.

**Comment by Tilix4** [comment]
The figure directive is native in docutils so I think it'll be easy: https://docutils.sourceforge.io/docs/ref/rst/directives.html#id36

I think it could be considered as a regular image in the MD output.

**Comment by clayrisser** [comment]
@Tilix4 want to take a stab at it. The code that renders the document is in this file.

https://github.com/codejamninja/sphinx-markdown-builder/blob/master/sphinx_markdown_builder/markdown_writer.py

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
