### ISSUE TITLE
Missing plenty of nodes (notes, admonitions, labels, code-block, hlist, centered, glossary...)

### ISSUE THREAD

**Issue by yves-chevallier** [codejamninja/sphinx-markdown-builder#49]
I have written a small `rst` snippet to see what *sphinx-markdown-builder* has in its guts. I am currently not quite impressed, but I feel this project deserves some interest and some contribution. 

My intimate goal is to use this extension (or another) with Vuepress to generate a real SPA static site from a rST documentation. I am planning to write a custom builder/writer to support Markdown+HTML output. So in my case, I can use Vue components inside my markdown documents. 

Here some observations on the time said:

- `note` is not correctly translated. If translated into Vuepress, admonitions could use [Custom Containers](https://v1.vuepress.vuejs.org/guide/markdown.html#custom-containers). 
- `warning` a two lines warning should be translated as a description list that doesn't exist in Markdown :( 
- `numref` internal references don't seem to work here. I would be possible to have anchor HTML `[warning](#warning)` and place an anchor in the document.
- `code-block` language. The language used should be added after the opening block
- `math`, The math environment is not supported :(
- `table` They are not working :(
- Various tables are not properly translated. I guess the best option is to translate them in HTML and inject the HTML directly into the Markdown.
- `glossary` : not supported

```rst
.. All Directives documentation master file, created by
   sphinx-quickstart on Sun Aug 16 19:21:50 2020.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to All Directives's documentation!
==========================================

.. toctree::
   :maxdepth: 2
   :caption: Contents:

This is some **bold** text and some *italic* one. Here a `link <http://google.fr>`_ And an internal ref :numref:`warning`.
.. note::

    This function is not suitable for sending spam e-mails.

.. _warning:

.. warning::

    The *spam* parameter

.. centered:: Some centred text

.. hlist::
    :columns: 3

    * A list of
    * short items
    * that should be
    * displayed
    * horizontally

.. code-block:: c

    void main(void) {
        int i = 2;
    }

.. glossary::

   term 1 : A
   term 2 : B
      Definition of both terms.

.. math::

   (a + b)^2 = a^2 + 2ab + b^2
   (a - b)^2 = a^2 - 2ab + b^2

.. productionlist::
   try_stmt: try1_stmt | try2_stmt
   try1_stmt: "try" ":" `suite`
            : ("except" [`expression` ["," `target`]] ":" `suite`)+
            : ["else" ":" `suite`]
            : ["finally" ":" `suite`]
   try2_stmt: "try" ":" `suite`
            : "finally" ":" `suite`

+------------------------+------------+----------+----------+
| Header row, column 1   | Header 2   | Header 3 | Header 4 |
| (header rows optional) |            |          |          |
+========================+============+==========+==========+
| body row 1, column 1   | column 2   | column 3 | column 4 |
+------------------------+------------+----------+----------+
| body row 2             | Cells may span columns.          |
+------------------------+------------+---------------------+
| body row 3             | Cells may  | - Table cells       |
+------------------------+ span rows. | - contain           |
| body row 4             |            | - body elements.    |
+------------------------+------------+---------------------+

+--------------+----------+-----------+-----------+
| row 1, col 1 | column 2 | column 3  | column 4  |
+--------------+----------+-----------+-----------+
| row 2        | Use the command ``ls more``.     |
+--------------+----------+-----------+-----------+
| row 3        |          |           |           |
+--------------+----------+-----------+-----------+

.. table:: Some caption

    =====  =====  =======
    A      B      A and B
    =====  =====  =======
    False  False  False
    True   False  False
    False  True   False
    True   True   True
    =====  =====  =======

.. figure:: https://nice-assets.s3-accelerate.amazonaws.com/smart_templates/8709f94969aca8c1dee0eb33eda98ec3/assets/preview_afcafb91b9af067cb34ed46d7f074c1c.jpg

    Some caption

- List
- With

  - An indented number of items
  - Here

    .. code-block:: text

       With some code here

A description
    This is a description

Another description
    With some other things


Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

```

**Comment by clayrisser** [comment]
I really appreciate this. That was my original goal when I started this.

**Comment by clayrisser** [comment]
Speaking of this, I’ve been working on a tool to create documentation pipelines to make it easy to move documentation through a pipeline. For example...

docs -> sphinx -> pandoc -> gatsby

https://github.com/codejamninja/pipedoc

**Comment by clayrisser** [comment]
https://github.com/codejamninja/pipedoc/blob/master/example/.pipedocrc

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
