### ISSUE TITLE
Misalignment of elements for nested lists

### ISSUE THREAD

**Issue by pmatulis** [codejamninja/sphinx-markdown-builder#53]
Misalignment of elements for nested lists are present in the Markdown output. What part of the code handles this?

### Input:

```
1. parent list item

   text

   * child list item

     text

     .. code-block:: none

        command
        command

     text
```

### Current output:

```
1. parent list item

text	   			<<==== misalignment (text after parent list item)

    * child list item

text				<<==== misalignment (text after child list item)

```none				<<==== misalignment (code block after child list item)
command				<<==== (ditto)
command				<<==== (ditto)
```				<<==== (ditto)

text				<<==== misalignment (text after child list item and code block)
```

### Desired output:

```
1. parent list item

   text

    * child list item

      text

      ```none
      command
      command
      ```

      text
```

**Comment by liran-funaro** [comment]
@pmatulis I created a new plugin that addresses most issues with this implementation.
It also addresses this issue.

You can try it: https://github.com/liran-funaro/sphinx-markdown-builder
I haven't released an official version yet, so you'll have to install it manually: 
```shell
pip3 uninstall sphinx-markdown-builder
pip3 install git+https://github.com/liran-funaro/sphinx-markdown-builder@main
```

**Comment by clayrisser** [comment]
@liran-funaro I am happy to forward people to your fork if you don't mind giving me some credit in your README.md and making a pull request in my README.md file. I no longer use this project, so I lack the motivation to properly maintain it.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
