### ISSUE TITLE
Several errors building to markdown Godot-Engine manual 

### ISSUE THREAD

**Issue by alexfreyre** [codejamninja/sphinx-markdown-builder#54]
Hi! This project is amazing. :smiley:  I'm looking forward to build all manuals I need to markdown to read them and consult them within [Obsidian](https://obsidian.md/), but I'm having some issues :disappointed: 

---

I want to build to markdown this project: 
- **source project files**  https://github.com/godotengine/godot-docs/tree/3.3

This is an example file from source:
- **source rst** [class_animatedsprite.txt](https://github.com/clayrisser/sphinx-markdown-builder/files/6407943/class_animatedsprite.txt) -  (renamed to .txt to upload it, github doesn't let upload rst files )

This is how it looks in html:
- **html reference** https://docs.godotengine.org/en/stable/classes/class_animatedsprite.html

And as a result several errors are shown in the build making really difficult to read this file in markdown:
- **markdown result** [class_animatedsprite.md](https://github.com/clayrisser/sphinx-markdown-builder/files/6407934/class_animatedsprite.md)

---

On the other hands the images were referenced in the text and they points to the right path but the folders weren't copied.

Is there any parameters to solve those issues or are they bugs?

**Comment by clayrisser** [comment]
I think they are bugs. I’m not very actively working on this project at the moment, but I am accepting pull requests.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
