### ISSUE TITLE
Apply to be Co-Maintainer of sphinx-markdown-builder

### ISSUE THREAD

**Issue by SilverRainZ** [codejamninja/sphinx-markdown-builder#59]
I had sent mail to you but get no response, so I file issue here :)

---

Hello clayrisser,
 
I am a power Sphinx user[1] and I wrote many Sphinxextensions[2].
 
sphinx-markdown-builder is a awesome project, but it has some BUGs.
I filed a PR[3] to fix one of theme, I hope it can be merged.
But it seems that you are no longer active on this project. Contribute is
always better than fork, can I apply to be the co-maintainer of this project?
 
If you agree, please also add me[4] as Co-Maintainer on pypi.
 
[1] https://github.com/SilverRainZ/bullet/blob/master/conf.py
[2] https://github.com/sphinx-notes
[3] https://github.com/clayrisser/sphinx-markdown-builder/pull/57
[4] https://pypi.org/user/SilverRainZ/
 
--
Best regards,
Shengyu Zhang
 
https://silverrainz.me/

**Comment by jenstroeger** [comment]
Thanks @SilverRainZ for your issue, I was wondering myself if this project is still active! @clayrisser, if you could please shed some light at the current status and future plans, that’d be helpful…

**Comment by odoublewen** [comment]
@clayrisser  +1 for the work on this sphinx extension.  

If you don't have time to maintain it (very understandable), then +100 if you would kindly open it up to co-maintainers!

A logical place for this repo to live would be under https://github.com/sphinx-contrib 

I encourage you to consider moving it there and accepting co-maintainers.

**Comment by jenstroeger** [comment]
@odoublewen please take a look at [sphinx-notes/markdown-builder](https://github.com/sphinx-notes/markdown-builder) and if you’d like to join ping @SilverRainZ.

**Comment by odoublewen** [comment]
Thank you @jenstroeger, good to know.

It would still be great to get @clayrisser to coordinate/cooperate on this.  (e.g. to be able to publish updated versions to the same pypi namespace.)

Ideally, instead of forking, THIS repo would be opened up to additional maintainer(s), or transferred to another org (sphinx-notes would be fine, though sphinx-contrib is a more natural home.)  That way we keep issue history, etc.

**Comment by SilverRainZ** [comment]
@clayrisser Kindly ping :)
