### ISSUE TITLE
Lists have too much blank space

### ISSUE THREAD

**Issue by nedbat** [codejamninja/sphinx-markdown-builder#61]
This .rst:
```
Simple Lists
------------

- Item 1
- Item 2
- Item 3
```

is output as:
```
# Simple Lists


* Item 1


* Item 2


* Item 3
```

When rendered, this puts too much space between the list items.

It renders on GitHub like this:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/23789/161407580-a029af8c-19b0-4a3c-86bd-167161b07de6.png">

If the markdown instead were this:
```
# Simple Lists

* Item 1
* Item 2
* Item 3
```

then it would render as:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/23789/161407585-459b4e44-0f8c-4b56-a531-481937dff337.png">

**Comment by nedbat** [comment]
This is fixed by #57.  Can we get a new release?

**Comment by liran-funaro** [comment]
@nedbat I created a new plugin that addresses most issues with this implementation.
It also addresses the excessive line breaks.
You can try it: https://github.com/liran-funaro/sphinx-markdown-builder
I haven't released an official version yet, so you'll have to install it manually: 
```shell
pip3 uninstall sphinx-markdown-builder
pip3 install git+https://github.com/liran-funaro/sphinx-markdown-builder@main
```

**Comment by clayrisser** [comment]
@liran-funaro I am happy to forward people to your fork if you don't mind giving me some credit in your README.md and making a pull request in my README.md file. I no longer use this project, so I lack the motivation to properly maintain it.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
