### ISSUE TITLE
Add `singlemarkdown` mode to help with internal project development

### ISSUE THREAD

**Issue by whardier** [codejamninja/sphinx-markdown-builder#62]
Being able to produce a single README.md that has the entire output would be valuable for teams using products like GitHub that want to make sure there is "go to" documentation for every repository.

**Comment by jenstroeger** [comment]
@whardier take a look at the [sphinx-notes/markdown-builder](https://github.com/sphinx-notes/markdown-builder) repo, it’s a tad more active.

**Comment by whardier** [comment]
Well.. that's just confusing.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
