### ISSUE TITLE
Linked file extension

### ISSUE THREAD

**Issue by realsontaran** [codejamninja/sphinx-markdown-builder#64]
Hi currently in generated index.md file contents linked like this
`[h2 Heading](dep/base.md#h2-heading)`

How can I configure this to generating links without .md file extension like this
`[h2 Heading](dep/base#h2-heading)`

**Comment by liran-funaro** [comment]
@realsontaran I created a new plugin that addresses most issues with this implementation.
It supports a configuration of the reference suffix. In your case, you should add the following to your `conf.py` file:
```python
markdown_uri_doc_suffix = ""
```

You can try it: https://github.com/liran-funaro/sphinx-markdown-builder
I haven't released an official version yet, so you'll have to install it manually: 
```shell
pip3 uninstall sphinx-markdown-builder
pip3 install git+https://github.com/liran-funaro/sphinx-markdown-builder@main
```

**Comment by clayrisser** [comment]
@liran-funaro I am happy to forward people to your fork if you don't mind giving me some credit in your README.md and making a pull request in my README.md file. I no longer use this project, so I lack the motivation to properly maintain it.

**Comment by liran-funaro** [comment]
Thanks.

I already credited you (and your brother I presume) in the readme.
If you have some other phrasing you'd like me to use please let me know.

Do you want me to open a PR for your readme that refers to my project?

One last thing, can you remove your plugin from PiPy so I'll add mine instead?

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
