### ISSUE TITLE
Add table support

### ISSUE THREAD

**Issue by clayrisser** [codejamninja/sphinx-markdown-builder#7]
I have already implemented table support, but I'm am not sure how well it works across different setups. Feedback would be much appreciated.

I am keeping track of where I am in the table to hopefully make it easy to add support for nested tables in the future. Keeping track of where you are is a simple pop/push operation. Push (append) the current node to the node type array when the node is entered, and pop it off the node type array when the node is departed.

```py
    def visit_table(self, node):
        self.tables.append(node)

    def depart_table(self, node):
        self.tables.pop()
```

Notice that I'm doing this with other nodes besides the table node. For example, I do this with `thead`, `tbody` and `row`.

```py
    def visit_row(self, node):
        if not len(self.theads) and not len(self.tbodys):
            raise nodes.SkipNode
        self.rows.append(node)

    def depart_row(self, node):
        self.add('|\n')
        if not len(self.theads):
            self.row_entries = []
        self.rows.pop()
```

Keeping track of where you are in the table (basically reference counting) simplifies the code. Instead of using integer counters, I am using arrays of nodes. This allows referencing the nodes from other visit methods. This can come in handy quite often. For example, I use the "reference counting node arrays" to generate padding in the table entries making the tables look much prettier.

Basically, I am finding the largest string in a column and using it to calculate the padding. This would be very challenging if I did not have access to nodes outside of the current node.

```py
    @property
    def rows(self):
        rows = []
        if not len(self.tables):
            return rows
        for node in self.tables[len(self.tables) - 1].children:
            if isinstance(node, nodes.row):
                rows.append(node)
            else:
                for node in node.children:
                    if isinstance(node, nodes.row):
                        rows.append(node)
        return rows

    def depart_entry(self, node):
        length = 0
        i = len(self.row_entries) - 1
        for row in self.rows:
            if len(row.children) > i:
                entry_length = len(row.children[i].astext())
                if entry_length > length:
                    length = entry_length
        padding = ''.join(_.map(range(length - len(node.astext())), lambda: ' '))
        self.add(padding + ' ')
```

https://github.com/codejamninja/sphinx-markdown-builder/blob/master/sphinx_markdown_builder/markdown_writer.py#L320-L329

I am thinking about possibly implementing this reference counting across all of the nodes. It could simplify the design of some of the more complex transpiling.

Please discuss the reference counting more at the issue below.
#8

**Comment by Liam-Deacon** [comment]
Hi @codejamninja - I have tried generating a markdown table from a rst file and all I get is rows beginning with a single `|` and no other content. I forked the automodule example from utf for #5 and added an example ReST table to `index.rst` at https://github.com/Lightslayer/sphinx-automodule-example.

For example the following table:

```restructuredtext

+----------------------------------------------------------------------+----------------------------+---------------------------------------------------------------------------+
| Package                                                              | License                    | Notes                                                                     |
+======================================================================+============================+===========================================================================+
| `NavPy == 1.0 <https://navpy.readthedocs.io/en/latest/>`_            | BSD                        | NavPy is pretty cool                                                      |
+----------------------------------------------------------------------+----------------------------+---------------------------------------------------------------------------+
| `aero-calc >= 0.13.2 <https://pypi.org/project/aero-calc/>`_         | BSD                        | Forked from `AeroCalc <https://kilohotel.com/python/aerocalc/>`_).        |
|                                                                      |                            | Used in aerospace stuff.                                                  |
+----------------------------------------------------------------------+----------------------------+---------------------------------------------------------------------------+
```

Becomes simply the following in the markdown build output:

```
|
|
|
|
```

The number of pipes seems to match the number of ReST table rows starting with `|`.

Any assistance on getting this working would be greatly appreciated!

P.S. The `.. automodule::` directive seems to be working well in the latest release (0.4.0) - Thanks 👍

**Comment by clayrisser** [comment]
Cool, could you send me a link to a repo that reproduces this issue? I'd love to try and fix it.

**Comment by Liam-Deacon** [comment]
Hi @codejamninja - I forked UTF's automodule example and added an example table to index.rst as part of commit [f99e2fd](https://github.com/Lightslayer/sphinx-automodule-example/commit/f99e2fd1e98be9a5439145ee888ce595542862dc) in https://github.com/Lightslayer/sphinx-automodule-example.

Essentially I ran the following:

```
git clone https://github.com/Lightslayer/sphinx-automodule-example
cd sphinx-automodule-example/docs
make html
make markdown
```

My setup is as follows:

```bash
$ python3 --version  # default system python3
Python 3.6.7
$ pip3 freeze | grep markdown
sphinx-markdown-builder==0.4.0
$ cat /etc/os-release | grep -E '^(VERSION|NAME)='
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
```

Any help in resolving this would be greatly appreciated :-)

**Comment by Liam-Deacon** [comment]
Just a quick update from me - I've updated the example project above and have relocated the table example to `docs/source/other.rst`. I'm struggling to get my head around the implementation and how the nodes work, but I find that changing the pipe symbols and adding some prints to `markdown_writer.py` has helped:

```python
    def visit_tgroup(self, node):
        print(md(node))
        pass

    def depart_tgroup(self, node):
        pass

    def visit_thead(self, node):
        if not len(self.tables):
            raise nodes.SkipNode
        self.theads.append(node)

    def depart_thead(self, node):
        for i in range(len(self.row_entries)):
            length = 0
            for row in self.rows:
                if len(row.children) > i:
                    entry_length = len(row.children[i].astext())
                    if entry_length > length:
                        length = entry_length
            print('Table length is: {}'.format(length))
            self.add('|@ ' + ''.join(_.map(range(length), lambda: '-')) + ' ')
        print('Table rows is: {}'.format(self.rows))
        self.add('|&\n')
        self.add('\n'.join(self.rows))
        self.row_entries = []
        self.theads.pop()

    def visit_tbody(self, node):
        if not len(self.tables):
            raise nodes.SkipNode
        print(convert_html2md(node))
        self.tbodys.append(node)

    def convert_html2md(node):
        raise NotImplementedError("This is where I got to!")
```

This gives me the following output:

```markdown
|^
|&
|^
|^
```

@codejamninja - do you have any pointers to help me understand how the nodes work?

**Comment by clayrisser** [comment]
Tables should be working now

**Comment by Liam-Deacon** [comment]
Hi @codejamninja - this is excellent news, good work! I'll try out tables support once I get a free moment :-)
