### ISSUE TITLE
Deprecate doctree2md.py

### ISSUE THREAD

**Issue by clayrisser** [codejamninja/sphinx-markdown-builder#9]
I think I would like to eventually deprecate `doctree2md.py`. Below are a few reasons for this thought.

* doctree2md.py was never fully finished (there are major features missing)
* doctree2md.py was never built with sphinx in mind
* doctree2md.py is a great reference, but I think the developers of sphinx-markdown-builder are getting a good grasp on how sphinx builders work
* I used doctree2md.py to jumpstart the sphinx-markdown-builder, not necessarily to sustain it 

Please give your feedback below

**Comment by odoublewen** [comment]
Yes, please remove.  At this point, it's confusing to have it in the source code.

**Comment by clayrisser** [comment]
DISCONTINUED: This project is no longer maintained. The active version of this project is now being maintained at [liran-funaro/sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder).
